baseURL: https://raminala1.netlify.app/
title: Ramin Ala
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
    - identifier: Publications
      name: Publications
      url: /Publications/
      weight: 4
params:
  author: John Doe
  description: An Electrical engineer with experience in RF and interest in data science.
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: https://github.com/raminala
    - icon: linkedin
      name: Linkedin
      url: https://www.linkedin.com/in/ramin-ala-6645b3188/
    - icon: twitter
      name: Twitter
      url: https://twitter.com/ala_ramin
