---
title: Final Project- 6636
author: ''
date: '2021-07-28'
slug: []
categories: []
tags:
  - Classification
  - data_visualization
  - data_wrangling
---

## import two dataset and rename variables

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)

bureau <- read_csv("Credit_Bureau.csv") %>%
  janitor::clean_names() %>%
rename(
    id= application_id,
    auto_loan= presence_of_open_auto_loan ,
    home_loan= presence_of_open_home_loan,
    trades_6m= no_of_trades_opened_in_last_6_months,
    inquiries_6m = no_of_inquiries_in_last_6_months_excluding_home_auto_loans,
    inquiries_12m= no_of_inquiries_in_last_12_months_excluding_home_auto_loans,
    utilization_12m =avgas_cc_utilization_in_last_12_months,
    trades_opened_12m =no_of_trades_opened_in_last_12_months,
    pl_trades_12m=no_of_pl_trades_opened_in_last_12_months,
    pl_trades_6m=no_of_pl_trades_opened_in_last_6_months,
   dpd_60_6m =  no_of_times_60_dpd_or_worse_in_last_6_months,
   dpd_90_12m =  no_of_times_90_dpd_or_worse_in_last_12_months,
   dpd_30_12m =  no_of_times_30_dpd_or_worse_in_last_12_months,
   dpd_90_6m =  no_of_times_90_dpd_or_worse_in_last_6_months,
   dpd_30_6m =  no_of_times_30_dpd_or_worse_in_last_6_months,
   dpd_60_12m =  no_of_times_60_dpd_or_worse_in_last_12_months
    )
    
names(bureau)

demogs<- read_csv("demogs.csv") %>%
  janitor::clean_names() %>%
rename(
    id= application_id,
    marital= marital_status_at_the_time_of_application,
    dependents= no_of_dependents,
    residence=type_of_residence,
    company_months =no_of_months_in_current_company,
    residence_months =no_of_months_in_current_residence
    )


names(demogs)
```



## bind two dataset to build master dataset


```{r}

bind_dataset <- left_join(demogs, bureau, 'id') %>%
  subset(select = -performance_tag.y) %>%
  rename(performance_tag=performance_tag.x)

names(bind_dataset)

```


## Reordering columns (place performance_tag at the end)

```{r}
col_order <- c("id", "age", "gender", "marital", "dependents", "income",
               "education", "profession", "residence", "residence_months", "company_months", "dpd_90_6m",
               "dpd_60_6m", "dpd_30_6m", "dpd_90_12m", "dpd_60_12m", "dpd_30_12m", "utilization_12m",
               "trades_6m", "trades_opened_12m", "pl_trades_6m", "pl_trades_12m", "inquiries_6m", "inquiries_12m",
               "home_loan", "outstanding_balance", "total_no_of_trades",  "auto_loan",
               "performance_tag"
               )
master <- bind_dataset[, col_order]


write.csv(master,
          "C:\\Fundamentals of Analytics\\master.csv", row.names = FALSE)
```




## weight of evidence (WOE) (and, equivalently, information value analysis)

## 4 : Data Preparation

```{r}
library(Information)

#summary(bureau)
#master$age <- factor(master$age)


master_IV <- master %>%

na.omit(master) %>%
subset(select=-id)


```


## 5 : Compute Information Value and WOE

```{r}
IV <- create_infotables(data=master_IV, y="performance_tag", bins=10, parallel=FALSE)
```

```{r}
IV_Value = data.frame(IV$Summary)

print(IV_Value)
```


```{r}
plot_infotables(IV, IV$Summary$Variable[1:27], same_scale=FALSE)

plot_infotables(IV, "inquiries_12m")
plot_infotables(IV, "age")
```


```{r}
tt <- master_IV %>%
  select(inquiries_12m, performance_tag) %>%
  
  group_by(performance_tag) %>%
  count()



vv <- master_IV %>%
  select(inquiries_12m, performance_tag) %>%
  filter(between(inquiries_12m,5,5)) %>%
  group_by(performance_tag) %>%
  count()
tt
vv
```


## Replace variables' values by the corresponding WOE value

```{r}

woe_data <- master %>%
  mutate( age = replace(age, between(age,-3,30),  -0.039506890)) %>%
  mutate( age = replace(age, between(age,31,35),   0.046882216)) %>%
  mutate( age = replace(age, between(age,36,38),   0.066531127)) %>%
  mutate( age = replace(age, between(age,39,41),   0.075316247)) %>%
  mutate( age = replace(age, between(age,42,44),  -0.061320756)) %>%
  mutate( age = replace(age, between(age,45,47),  -0.004329305)) %>%
  mutate( age = replace(age, between(age,48,50),  -0.007207997)) %>%
  mutate( age = replace(age, between(age,51,53),  -0.137458080)) %>%
  mutate( age = replace(age, between(age,54,57),   0.044718393)) %>%
  mutate( age = replace(age, between(age,58,65),  -0.013404982)) %>%
  
  mutate( gender = replace(gender, gender=="F",  0.028254108)) %>%
  mutate( gender = replace(gender, gender=="M",  -0.008890893)) %>%
  
  mutate( marital = replace(marital, marital=="Married",  -0.004058593)) %>%
  mutate( marital = replace(marital, marital=="Single",  0.023087052)) %>% 
  
  mutate( dependents = replace(dependents, dependents==1,  0.047511301)) %>%
  mutate( dependents = replace(dependents, dependents==2, -0.089738973)) %>% 
  mutate( dependents = replace(dependents, dependents==3,  0.051725860)) %>%
  mutate( dependents = replace(dependents, dependents==4, -0.029168607)) %>% 
  mutate( dependents = replace(dependents, dependents==5,  0.006997003)) %>%
  
  mutate( income = replace(income, between(income,-0.5,5),  0.299553096)) %>%
  mutate( income = replace(income, between(income,6,10),    0.270245403)) %>%
  mutate( income = replace(income, between(income,11,16),   0.074864917)) %>%
  mutate( income = replace(income, between(income,17,21),   0.089160195)) %>%
  mutate( income = replace(income, between(income,22,26),   0.007652167)) %>%
  mutate( income = replace(income, between(income,27,31),   0.071544388)) %>%
  mutate( income = replace(income, between(income,32,36),  -0.138694556)) %>%
  mutate( income = replace(income, between(income,37,41),  -0.264723534)) %>%
  mutate( income = replace(income, between(income,42,48),   -0.175401898)) %>%
  mutate( income = replace(income, between(income,49,60),  -0.363216455)) %>%

  mutate( education = replace(education, education=="Bachelor",  0.0203476113)) %>%
  mutate( education = replace(education, education=="Masters",  -0.0008907703)) %>%
  mutate( education = replace(education, education=="Others",  0.5394285801)) %>%
  mutate( education = replace(education, education=="Phd",  -0.0085173636)) %>%
  mutate( education = replace(education, education=="Professional",  -0.0155472553)) %>%
  
  mutate( profession = replace(profession, profession=="SAL",  -0.02719623)) %>%
  mutate( profession = replace(profession, profession=="SE",  0.09099464)) %>%
  mutate( profession = replace(profession, profession=="SE_PROF",  -0.01586440)) %>% 
  
  mutate( residence = replace(residence, residence=="Company provided",  0.066903551)) %>%
  mutate( residence = replace(residence, residence=="Living with Parents",  0.074093102)) %>%
  mutate( residence = replace(residence, residence=="Others",  -0.514160027)) %>%
  mutate( residence = replace(residence, residence=="Owned",  -0.003167738	)) %>%
  mutate( residence = replace(residence, residence=="Rented",  -0.002327681)) %>%
  
  mutate( residence_months = replace(residence_months, between(residence_months,6,9),  -0.27504521)) %>%
  mutate( residence_months = replace(residence_months, between(residence_months,10,28),  0.50219013)) %>%
  mutate( residence_months = replace(residence_months, between(residence_months,29,49),  0.30145219)) %>%
  mutate( residence_months = replace(residence_months, between(residence_months,50,72),  0.14236553)) %>%
  mutate( residence_months = replace(residence_months, between(residence_months,73,97),  0.13184356)) %>%
  mutate( residence_months = replace(residence_months, between(residence_months,98,126),  -0.07614037)) %>%

  mutate( company_months = replace(company_months, between(company_months,3,5),  0.10380388)) %>%
  mutate( company_months = replace(company_months, between(company_months,6,12),  0.17693458)) %>%
  mutate( company_months = replace(company_months, between(company_months,13,19),  0.20495867)) %>%
  mutate( company_months = replace(company_months, between(company_months,20,26),  0.03865713)) %>%
  mutate( company_months = replace(company_months, between(company_months,27,33),  -0.08128390)) %>%
  mutate( company_months = replace(company_months, between(company_months,34,40),  0.01916403)) %>%
  mutate( company_months = replace(company_months, between(company_months,41,47),  -0.15950171)) %>%
  mutate( company_months = replace(company_months, between(company_months,48,53),  -0.22066994)) %>%
  mutate( company_months = replace(company_months, between(company_months,54,61),  -0.23006158)) %>%
  mutate( company_months = replace(company_months, between(company_months,62,133),  0.06500409)) %>%

  mutate( dpd_90_6m = replace(dpd_90_6m, dpd_90_6m==0,  -0.2664307)) %>%
  mutate( dpd_90_6m = replace(dpd_90_6m, between(dpd_90_6m,1,3), 0.6239753))  %>%
  
  mutate( dpd_60_6m = replace(dpd_60_6m, dpd_60_6m==0,  -0.3435695)) %>%
  mutate( dpd_60_6m = replace(dpd_60_6m, between(dpd_60_6m,1,5),  0.6230040))  %>%
  
  mutate( dpd_30_6m = replace(dpd_30_6m, dpd_30_6m==0,  -0.3958799)) %>%
  mutate( dpd_30_6m = replace(dpd_30_6m, dpd_30_6m==1,  0.4694610))  %>%
  mutate( dpd_30_6m = replace(dpd_30_6m, between(dpd_30_6m,2,7),  0.7403884)) %>%

  mutate( dpd_90_12m = replace(dpd_90_12m, dpd_90_12m==0,  -0.3647314)) %>%
  mutate( dpd_90_12m = replace(dpd_90_12m, dpd_90_12m==1,  0.5101573))  %>%
  mutate( dpd_90_12m = replace(dpd_90_12m, between(dpd_90_12m,2,5),  0.7218272)) %>%

  mutate( dpd_60_12m = replace(dpd_60_12m, dpd_60_12m==0,  -0.3591009)) %>%
  mutate( dpd_60_12m = replace(dpd_60_12m, dpd_60_12m==1,  0.2152035))  %>%
  mutate( dpd_60_12m = replace(dpd_60_12m, between(dpd_60_12m,2,7),  0.6939493)) %>%
  
  mutate( dpd_30_12m = replace(dpd_30_12m, dpd_30_12m==0,  -0.3853646)) %>%
  mutate( dpd_30_12m = replace(dpd_30_12m, between(dpd_30_12m,1,2),  0.2848629))  %>%
  mutate( dpd_30_12m = replace(dpd_30_12m, between(dpd_30_12m,3,9),  0.7965947))   %>%
  
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,0,4),  -0.79974940)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,5,6),  -0.79817351)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,7,8),  -0.79187508)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,9,11),  -0.66998411)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,12,14),  -0.46603868)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,15,21),  -0.07600819)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,22,37),  0.47376425)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,38,51),  0.58503960)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,52,71),  0.56644494)) %>%
  mutate( utilization_12m = replace(utilization_12m, between(utilization_12m,72,113),  0.38568829)) %>%
  
  mutate( trades_6m = replace(trades_6m, trades_6m==0,  -0.7402284	)) %>%
  mutate( trades_6m = replace(trades_6m, trades_6m==1,  -0.4760898	)) %>%
  mutate( trades_6m = replace(trades_6m, trades_6m==2,  0.2364562)) %>%
  mutate( trades_6m = replace(trades_6m, trades_6m==3,  0.4327520)) %>%
  mutate( trades_6m = replace(trades_6m, trades_6m==4,  0.5215066)) %>%
  mutate( trades_6m = replace(trades_6m, between(trades_6m,5,12),  0.1335172))%>%
  
  mutate( trades_opened_12m = replace(trades_opened_12m, trades_opened_12m==0,  -0.894500098)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, trades_opened_12m==1,  -1.016850939)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, trades_opened_12m==2,  -0.813563496)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, between(trades_opened_12m,3,4),  0.011943065)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, trades_opened_12m==5,  0.207396853)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, between(trades_opened_12m,6,7),  0.448049021)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, between(trades_opened_12m,8,9),  0.573136724)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, between(trades_opened_12m,10,12),  0.485011064)) %>%
  mutate( trades_opened_12m = replace(trades_opened_12m, between(trades_opened_12m,13,28),  0.002793356)) %>%
  
  mutate( pl_trades_6m = replace(pl_trades_6m, pl_trades_6m==0,  -0.6768231)) %>%
  mutate( pl_trades_6m = replace(pl_trades_6m, pl_trades_6m==1,  0.2013560)) %>%
  mutate( pl_trades_6m = replace(pl_trades_6m, pl_trades_6m==2,  0.4397232)) %>%
  mutate( pl_trades_6m = replace(pl_trades_6m, between(pl_trades_6m,3,6),  0.3576285))%>%
  
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==0,  -0.9471609	)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==1,  -0.1279522	)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==2,  0.2522636)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==3,  0.4161652)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==4,  0.5016385)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, pl_trades_12m==5,  0.4196919)) %>%
  mutate( pl_trades_12m = replace(pl_trades_12m, between(pl_trades_12m,6,12),  0.2376102))%>%

  mutate( inquiries_6m = replace(inquiries_6m, inquiries_6m==0,  -0.75470945)) %>%
  mutate( inquiries_6m = replace(inquiries_6m, inquiries_6m==1,  0.18011102)) %>%
  mutate( inquiries_6m = replace(inquiries_6m, inquiries_6m==2,  0.21415526)) %>%
  mutate( inquiries_6m = replace(inquiries_6m, between(inquiries_6m,3,4),  0.50749871)) %>%
  mutate( inquiries_6m = replace(inquiries_6m, between(inquiries_6m,5,10),  0.01163274)) %>%
  
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==0,  -1.14210740)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==1,  -0.02178118)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==2,   0.14294109)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==3,   0.16773844)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==4,   0.25020441)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, inquiries_12m==5,   0.57635386)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, between(inquiries_12m,6,8),  0.48580800)) %>%
  mutate( inquiries_12m = replace(inquiries_12m, between(inquiries_12m,9,20),  0.01255320))  %>%
  
  mutate( home_loan = replace(home_loan, home_loan==0,  0.07322469)) %>%
  mutate( home_loan = replace(home_loan, home_loan==1, -0.23694925))%>%
  
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,0,7786),  -0.9764093)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,7787,55454),  -0.8487953)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,56065,392876),  -0.0769904)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,392909,590337),   0.2715642)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,590343,777938),   0.4655003)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,777956,976179),   0.4142887)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,976183,1362849),   0.3866071)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,1362864,2962106),  -0.3887941)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,2962114,3289876),  -0.8015947)) %>%
  mutate( outstanding_balance = replace(outstanding_balance, between(outstanding_balance,3289931,5218801),   0.2963591)) %>%


  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==1,  -1.05653995)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==2,   -1.01505568	)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==3,   -0.69881486)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==4,  -0.44466272)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==5,  -0.04461396)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, between(total_no_of_trades,6,7),  0.21585574)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, total_no_of_trades==8,   0.46328513)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, between(total_no_of_trades,9,10),  0.54093915)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, between(total_no_of_trades,11,19),  0.42543258)) %>%
  mutate( total_no_of_trades = replace(total_no_of_trades, between(total_no_of_trades,20,44),  -0.06846777	)) %>%
  
  mutate( auto_loan = replace(auto_loan, auto_loan==0,  0.01191341	)) %>%
  mutate( auto_loan = replace(auto_loan, auto_loan==1,   -0.13519714	))



  print(IV$Tables$dpd_60_6m, row.names=FALSE)
  names(woe_data)
  
  write.csv(woe_data,
          "C:\\Fundamentals of Analytics\\woe_data.csv", row.names = FALSE)
```

## Support Vector Machines

```{r}
library(e1071)
```

```{r}


svmfit = svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
print(svmfit)
```