---
title: 'Assignment A02: Classification Models-revision'
author: ''
date: '2021-07-25'
slug: []
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<p><strong><em>Ramin Ala</em></strong></p>
<div id="executive-summary" class="section level2">
<h2>Executive Summary</h2>
<p>The data is related to direct marketing campaigns (based on phone calls) of a Portuguese banking institution. This is a <strong>supervised question</strong> because it has an outcome (y), which is defined as if the product (bank term deposit) would be (or not) subscribed, “yes” means subscribed, and “no” means did not subscribe. This dataset consists of <strong>4521 observations</strong>..</p>
<p>In addition to the outcome classification variable, there are 16 variables. Eight variables are related to statistical information about current and previous campaigns, and they seem irrelevant to a dependent variable. So, there are eight determinant variables Including:</p>
<p>Customer’s <strong><em>age</em></strong> and <strong><em>balance</em></strong> (numerical variables),</p>
<p>Customer’s <strong><em>job</em></strong>, <strong><em>marital</em></strong> status, <strong><em>education</em></strong> (categorical variables)</p>
<p><strong><em>housing loan</em></strong>, <strong><em>personal loan</em></strong>, and <strong><em>default status</em></strong> (binary variables)</p>
<p>Information regarding the reference of the dataset is available at:</p>
<p><a href="http://www3.dsi.uminho.pt/pcortez/bib/2011-esm-1.txt" class="uri">http://www3.dsi.uminho.pt/pcortez/bib/2011-esm-1.txt</a></p>
</div>
<div id="univariate-analysis-of-numerical-variables" class="section level2">
<h2>Univariate Analysis of numerical variables</h2>
</div>
<div id="age" class="section level2">
<h2><em>age</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre><code>## # A tibble: 1 x 6
##   minimum    q1 median  mean    q3 maximum
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1      19    33     39  41.2    49      87</code></pre>
<p>This plot and table give an impression of the age of examined group. The minimum, maximum and average ages are 19, 87, and 41 years respectively. The majority of observations are concentrated at the age of between 30 to 35 years. This information would not provide any insight into the possible outcome.</p>
</div>
<div id="balance" class="section level2">
<h2><em>balance</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre><code>## # A tibble: 1 x 6
##   minimum    q1 median  mean    q3 maximum
##     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1   -3313    69    444 1423.  1480   71188</code></pre>
<p>Balance is generally between 0 to $500, however, amounts as high as $71000 is available in data. In the above plot, Only range from $-4000 to $10000 is shown for a better depiction. In this case, mean (1422) is higher than median (444) and plor looks right-skewed.</p>
</div>
<div id="univariate-analysis-of-some-catagorical-variables" class="section level2">
<h2>Univariate Analysis of some catagorical variables</h2>
</div>
<div id="subscription-status" class="section level2">
<h2><em>subscription status</em></h2>
<pre><code>## # A tibble: 2 x 3
## # Groups:   y [2]
##   y         n percentage
##   &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 no     4000       88.5
## 2 yes     521       11.5</code></pre>
<p>This univariate analysis could give a clue about probability of subscription in customers. from the above table, it is obvious that majority of customers did not subscribe (88.476%) comparing slightly more than ten percent of customers who finally choose to subscribe (11.524%). The good point about dataset is it provided valid outcomes for all customers (whether subscribed or not).</p>
</div>
<div id="bivariate-analysis" class="section level2">
<h2>Bivariate Analysis</h2>
<p>In this part, two variables are considering and their relationship is examined. A dummy variable has been defined for outcomes so that</p>
<p>0=No (did not subscribe), and</p>
<p>1=yes (subscribed).</p>
</div>
<div id="correlation-between-age-and-balance" class="section level2">
<h2>correlation between age and balance</h2>
<pre><code>## [1] &quot;correlation between age and balance:  0.0838201422447776&quot;</code></pre>
<p>It shows a small positive correlation between age and balance. Generally, older clients tend to have a higher balance but the correlation is more like a random relation because it is more close to zero (random case) than 1 (strong correlation). It shows that these two parameters cannot be assessed from each other. On the other hand, highly correlated variables are not good predictors together because they follow the same trend.</p>
</div>
<div id="subscription-statusjob" class="section level2">
<h2><em>subscription status~job</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>There are twelve categories of jobs. Managements, blue-collars, and technicians are the most frequent jobs among respondents. As shown in the plot, among these jobs, managements are more likely to subscribe. However, relative number of subscriptions is very high among students, unknown and unemployed people. These groups are more likely to subscribe.</p>
</div>
<div id="subscription-statusmarital" class="section level2">
<h2><em>subscription status~marital</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Similar to previous analysis could be done for marital status. This plot shows a majority of respondents are married. However, divorced group are more likely to subscribe when numbers are compared in each group.</p>
</div>
<div id="subscription-statusbalance" class="section level2">
<h2><em>subscription status~balance</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>In this plot, subscription status versus balance is depicted. Very high balances (higher than $30000) are considered as outlier data and they have been omitted from plotting. Considering this plot alone is not very informative for me. I barely could decide if a higher balance increase/decrease the chance of subscription by looking at this plot. For this reason, a Generalized linear line was added to the plot for better information.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The added layer to this plot, comparing the previous plot, shows that those who have a higher balance are more likely to subscribe to a term deposit. But how strong is this relationship? In other word, is balance very determinant parameter? Let’s perform a generalized analysis and see the parameters.</p>
<pre><code>## 
## Call:
## glm(formula = subscription_status ~ balance, family = binomial, 
##     data = bank)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -0.8279  -0.4937  -0.4904  -0.4892   2.0976  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -2.063e+00  5.116e-02 -40.316   &lt;2e-16 ***
## balance      1.641e-05  1.370e-05   1.198    0.231    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3231.0  on 4520  degrees of freedom
## Residual deviance: 3229.7  on 4519  degrees of freedom
## AIC: 3233.7
## 
## Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div id="subscription-statusage" class="section level2">
<h2><em>subscription status~age</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Again it looks difficult to get information from this plot as they have not strong relation. However, blue line that is the generalized regression line, shows that higher age people tends to subscribe more. An important subject to remember is in a multi-variable problem, considering one parameter alone could be misleading because of correlation of variables.</p>
</div>
<div id="subscription-statusdefault" class="section level2">
<h2><em>subscription status~default</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>In this plot combination of two categorical variables are counted. One is default and the other is the dependent variable (result). We have four categories here (four possible combinations for two binary variables). It seems that default clients (default=yes) is very unlikely to subscribe.</p>
</div>
<div id="box-plot-for-subscription-status-versus-age" class="section level2">
<h2>Box plot for subscription status versus age</h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>In this plot, we take a look at the distribution of subscription_status by age of clients. Plots show age has a relatively low effect on the chance of subscription of a client. This will be proved later by multiple linear regression and looking at the coefficient of age and its p-value. Older clients have a slightly higher chance of subscription. This can be seen by comparing mean and third quartile lines.</p>
</div>
<div id="box-plot-for-subscription-status-versus-balance" class="section level2">
<h2>Box plot for subscription status versus balance</h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As it can be seen from this box plot, there are lots of outliers in the balance and variance of balance is high. Generally, it seems that higher balance increase chanse of subscription.</p>
</div>
<div id="analysis-of-three-variables-result-versus-age-and-balance" class="section level2">
<h2>Analysis of three variables: result versus age and balance</h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-15-1.png" width="672" />
This plot consists of two numerical variables (age and balance) that both are explanatory variables and the response variable which is depicted by color (pink colors did not subscribe and blue colors subscribed).</p>
</div>
<div id="analysis-of-four-variablessubscription-statusage-and-marital-and-loan" class="section level2">
<h2><em>Analysis of four variables:subscription status~age and marital and loan</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>This plot probably gives not more information than a two-variable analysis because points are very closed hard to distinguish. So it is time to examine all parameters using glm function.</p>
</div>
<div id="generalized-linear-model" class="section level2">
<h2>Generalized Linear Model</h2>
<pre><code>## 
## Call:
## glm(formula = subscription_status ~ age + job + marital + education + 
##     default + balance + housing + loan, family = binomial, data = bank)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.0264  -0.5385  -0.4425  -0.3564   2.6223  
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -1.932e+00  3.725e-01  -5.188 2.13e-07 ***
## age                 8.437e-03  5.734e-03   1.471   0.1412    
## jobblue-collar     -3.658e-01  1.976e-01  -1.851   0.0642 .  
## jobentrepreneur    -3.297e-01  3.141e-01  -1.050   0.2939    
## jobhousemaid       -6.485e-02  3.321e-01  -0.195   0.8452    
## jobmanagement      -1.225e-01  1.961e-01  -0.625   0.5319    
## jobretired          5.436e-01  2.465e-01   2.205   0.0274 *  
## jobself-employed   -2.588e-01  2.851e-01  -0.908   0.3641    
## jobservices        -2.735e-01  2.225e-01  -1.229   0.2191    
## jobstudent          4.532e-01  3.137e-01   1.445   0.1486    
## jobtechnician      -2.465e-01  1.857e-01  -1.327   0.1844    
## jobunemployed      -3.675e-01  3.299e-01  -1.114   0.2652    
## jobunknown          2.766e-01  4.590e-01   0.603   0.5467    
## maritalmarried     -3.947e-01  1.425e-01  -2.771   0.0056 ** 
## maritalsingle      -1.661e-02  1.655e-01  -0.100   0.9200    
## educationsecondary  2.162e-01  1.663e-01   1.300   0.1935    
## educationtertiary   4.237e-01  1.915e-01   2.212   0.0269 *  
## educationunknown   -1.751e-01  2.900e-01  -0.604   0.5460    
## defaultyes          1.861e-01  3.653e-01   0.510   0.6104    
## balance            -2.165e-07  1.468e-05  -0.015   0.9882    
## housingyes         -4.840e-01  1.011e-01  -4.787 1.69e-06 ***
## loanyes            -7.235e-01  1.679e-01  -4.310 1.64e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 3231.0  on 4520  degrees of freedom
## Residual deviance: 3096.5  on 4499  degrees of freedom
## AIC: 3140.5
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Pr(&gt;|z|) value for balance is close to 1 and this makes us believe it is not a determinant parameter, but this parameter is negligible for housing with relatively high value for its coefficient. This is the reason for importance of housing status. A similar circumstance is for loan status.</p>
<p>In addition, Coefficients of above analysis are all small because the number of respondents with subscribed status is very lower than not subscribed clients.</p>
<p>Finally, some parameters that seemed to be determinant in univariate analysis are not important in fact. This is because of correlation between non-determinant and determinant
variables.</p>
</div>
<div id="subscription-statuseducation" class="section level2">
<h2><em>subscription status~education</em></h2>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>From generalized linear model coefficient, it appears that education is a determinant factor, therefore an analysis of education and subscription status is performed here. This plot shows that most clients have secondary education, followed by tertiary, primary, and unknown education levels. Comparing the ratio of people who subscribed to those who did not subscribe in each category shows that people with tertiary education are more likely to finally subscribe.</p>
</div>
<div id="evaluating-performance-with-confusion-matrix" class="section level2">
<h2>Evaluating performance with confusion matrix</h2>
<p>It is important to assess accuracy of model. Although model should be assessed with test data (not previously seen data or data that is not used for building the model). In this part we will use model train data for assessment. We pass data to both single and multiple Logistic regression Models in order to classify whether clients associated with the given information in the train data set will subscribe to a term deposit. besides, we will evaluate the performance of the model by confusion matrix and heatmap plot.</p>
<p>First, start with evaluating the performance of a single logistic regression Model using heatmap matrix.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Here, We set the threshold to 0.2. After passing the data to SLR model, it shows 88.5% of predictions are accurate. There are 521 false-negative and 2 false-positive predictions.</p>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>We set threshold to 0.35 here. After passing the data SLR model, it shows 88.5% of predictions are accurate. There are 514 false-negative and 4 false-positive predictions.</p>
</div>
<div id="summary-of-findings" class="section level2">
<h2>Summary of findings</h2>
<ul>
<li><p>Most respondents in this campaign were 30 to 35 years old with near zero balance. Besides, nearly 90% of respondents did not subscribe finally.</p></li>
<li><p>Univariate analysis shows a positive slope for both age and balance (higher age/balance means a higher chance of subscription). However, generalized linear Modeling with consideration of all variables shows balance has not an impact on chance of subscription.</p></li>
<li><p>Univariate analysis of jobs shows that a big portion of students, unemployed, and those with unknown jobs subscribed, but respondents with blue-color jobs and technicians did not subscribe so often.</p></li>
<li><p>Divorced respondents were more likely to subscribe than married and single ones.</p></li>
<li><p>Generalized Linear Model shows that balance is not a determinant factor but housing and loan status are both determinants.</p></li>
<li><p>Coefficients of glm analysis are all small because the number of respondents with subscribed status is very lower than not subscribed clients.</p></li>
</ul>
</div>
