<!doctype html>
<html lang="en-us">
  <head>
    <title>Fitting and Interpreting Models // Ramin Ala</title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta charset="utf-8" />
    <meta name="generator" content="Hugo 0.83.1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="John Doe" />
    <meta name="description" content="" />
    <link rel="stylesheet" href="https://ramin1ala.netlify.app/css/main.min.9dbf51e978afe3857b6cf4f89e41949fcd0410a29b2c2a5da404b58dfd6fc228.css" />

    
    <meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Fitting and Interpreting Models"/>
<meta name="twitter:description" content="Import Librarieslibrary(tidyverse)library(tidymodels) #Interesting collections of models.library(ggtext) #similar to ggplot but for text.library(knitr)library(kableExtra) #for creating tables, more readable and nice fashion.set.seed(1234) #to get exactly same dataset each time sample from dataset (number is arbitrary like a key that are used each time).options(dplyr.print_min = 10, dplyr.print_max = 6)Models with numerical explanatory variablesImport Data: paris Paintingspp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))Number of observations: 3393Number of variables: 61Goal: Predict height from widthBelow is a LaTeX syntax in R markdown."/>

    <meta property="og:title" content="Fitting and Interpreting Models" />
<meta property="og:description" content="Import Librarieslibrary(tidyverse)library(tidymodels) #Interesting collections of models.library(ggtext) #similar to ggplot but for text.library(knitr)library(kableExtra) #for creating tables, more readable and nice fashion.set.seed(1234) #to get exactly same dataset each time sample from dataset (number is arbitrary like a key that are used each time).options(dplyr.print_min = 10, dplyr.print_max = 6)Models with numerical explanatory variablesImport Data: paris Paintingspp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))Number of observations: 3393Number of variables: 61Goal: Predict height from widthBelow is a LaTeX syntax in R markdown." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-06-15T00:00:00&#43;00:00" />
<meta property="article:modified_time" content="2021-06-15T00:00:00&#43;00:00" />



  </head>
  <body>
    <header class="app-header">
      <a href="https://ramin1ala.netlify.app/"><img class="app-header-avatar" src="/avatar.jpg" alt="John Doe" /></a>
      <h1>Ramin Ala</h1>
      <nav class="app-header-menu">
          <a class="app-header-menu-item" href="/">Home</a>
            ~
          
          <a class="app-header-menu-item" href="/tags/">Tags</a>
            ~
          
          <a class="app-header-menu-item" href="/about/">About</a>
            ~
          
          <a class="app-header-menu-item" href="/publications/">Publications</a>
      </nav>
      <p>An Electrical engineer with experience in RF and interest in data science.</p>
      <div class="app-header-social">
        
          <a href="https://github.com/raminala" target="_blank" rel="noreferrer noopener">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-github">
  <title>Github</title>
  <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
</svg>
          </a>
        
          <a href="https://www.linkedin.com/in/ramin-ala-6645b3188/" target="_blank" rel="noreferrer noopener">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-linkedin">
  <title>Linkedin</title>
  <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle>
</svg>
          </a>
        
          <a href="https://twitter.com/ala_ramin" target="_blank" rel="noreferrer noopener">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-twitter">
  <title>Twitter</title>
  <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
</svg>
          </a>
        
      </div>
    </header>
    <main class="app-container">
      
  <article class="post">
    <header class="post-header">
      <h1 class ="post-title">Fitting and Interpreting Models</h1>
      <div class="post-meta">
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-calendar">
  <title>calendar</title>
  <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line>
</svg>
          Jun 15, 2021
        </div>
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-clock">
  <title>clock</title>
  <circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>
</svg>
          7 min read
        </div>
        <div>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tag">
  <title>tag</title>
  <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7.01" y2="7"></line>
</svg>
              <a class="tag" href="https://ramin1ala.netlify.app/tags/r/">R</a>
        </div>
      </div>
    </header>
    <div class="post-content">
      
<script src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/header-attrs/header-attrs.js"></script>
<script src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/kePrint/kePrint.js"></script>
<link href="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/lightable/lightable.css" rel="stylesheet" />


<div id="import-libraries" class="section level2">
<h2>Import Libraries</h2>
<pre class="r"><code>library(tidyverse)
library(tidymodels) #Interesting collections of models.
library(ggtext) #similar to ggplot but for text.
library(knitr)
library(kableExtra) #for creating tables, more readable and nice fashion.

set.seed(1234) #to get exactly same dataset each time sample from dataset (number is arbitrary like a key that are used each time).

options(dplyr.print_min = 10, dplyr.print_max = 6)</code></pre>
</div>
<div id="models-with-numerical-explanatory-variables" class="section level1">
<h1>Models with numerical explanatory variables</h1>
<div id="import-data-paris-paintings" class="section level2">
<h2>Import Data: paris Paintings</h2>
<pre class="r"><code>pp &lt;- read_csv(&quot;paris-paintings.csv&quot;, na = c(&quot;n/a&quot;, &quot;&quot;, &quot;NA&quot;))</code></pre>
<ul>
<li>Number of observations: 3393</li>
<li>Number of variables: 61</li>
</ul>
</div>
<div id="goal-predict-height-from-width" class="section level2">
<h2>Goal: Predict height from width</h2>
<p>Below is a LaTeX syntax in R markdown.Wrap syntax in two pair of Dollar signs.</p>
<p><span class="math display">\[\widehat{height}_{i} = \beta_0 + \beta_1 \times width_{i}\]</span></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/figure-html/height-width-plot-1.png" width="672" /></p>
<hr />
<p>Below image shows different packages that are included in tidymodels.</p>
<p><img src="tidymodels.png" width="98%" /></p>
<hr />
</div>
<div id="step-1-specify-model" class="section level2">
<h2>Step 1: Specify model</h2>
<pre class="r"><code>linear_reg()</code></pre>
<pre><code>## Linear Regression Model Specification (regression)</code></pre>
<hr />
</div>
<div id="step-2-set-model-fitting-engine" class="section level2">
<h2>Step 2: Set model fitting <em>engine</em></h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) # lm: linear model</code></pre>
<pre><code>## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
<hr />
</div>
<div id="step-3-fit-model-estimate-parameters" class="section level2">
<h2>Step 3: Fit model &amp; estimate parameters</h2>
<p>… using <strong>formula syntax</strong></p>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ Width_in, data = pp) #in: inches #we want to predict height, using width</code></pre>
<pre><code>## parsnip model object
## 
## Fit time:  0ms 
## 
## Call:
## stats::lm(formula = Height_in ~ Width_in, data = data)
## 
## Coefficients:
## (Intercept)     Width_in  
##      3.6214       0.7808</code></pre>
<hr />
</div>
<div id="a-closer-look-at-model-output" class="section level2">
<h2>A closer look at model output</h2>
<pre><code>## parsnip model object
## 
## Fit time:  0ms 
## 
## Call:
## stats::lm(formula = Height_in ~ Width_in, data = data)
## 
## Coefficients:
## (Intercept)     Width_in  
##      3.6214       0.7808</code></pre>
<p><span class="math display">\[\widehat{height}_{i} = 3.6214 + 0.7808 \times width_{i}\]</span></p>
<hr />
</div>
<div id="a-tidy-look-at-model-output" class="section level2">
<h2>A tidy look at model output</h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ Width_in, data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    3.62    0.254        14.3 8.82e-45
## 2 Width_in       0.781   0.00950      82.1 0</code></pre>
<p><span class="math display">\[\widehat{height}_{i} = 3.62 + 0.781 \times width_{i}\]</span></p>
<hr />
</div>
<div id="slope-and-intercept" class="section level2">
<h2>Slope and intercept</h2>
<p>.large[<span class="math display">\[\widehat{height}_{i} = 3.62 + 0.781 \times width_{i}\]</span>]</p>
<hr />
<ul>
<li><strong>Slope:</strong> For each additional inch the painting is wider, the height is expected to be higher, on average, by 0.781 inches.</li>
</ul>
<hr />
<ul>
<li><strong>Intercept:</strong> Paintings that are 0 inches wide are expected to be 3.62 inches high, on average. (Does this make sense?)</li>
</ul>
<hr />
</div>
<div id="correlation-does-not-imply-causation" class="section level2">
<h2>Correlation does not imply causation</h2>
<p>Remember this when interpreting model coefficients</p>
<p><img src="cell_phones.png" width="90%" /></p>
<p>.footnote[Source: XKCD, <a href="https://xkcd.com/925/">Cell phones</a>]</p>
<hr />
<p>class: middle</p>
</div>
</div>
<div id="parameter-estimation" class="section level1">
<h1>Parameter estimation</h1>
<hr />
<div id="linear-model-with-a-single-predictor" class="section level2">
<h2>Linear model with a single predictor</h2>
<ul>
<li>We’re interested in <span class="math inline">\(\beta_0\)</span> (population parameter for the intercept) and <span class="math inline">\(\beta_1\)</span> (population parameter for the slope) in the following model:</li>
</ul>
<p><span class="math display">\[\hat{y}_{i} = \beta_0 + \beta_1~x_{i}\]</span></p>
<hr />
<ul>
<li>Tough luck, you can’t have them…</li>
</ul>
<hr />
<ul>
<li>So we use sample statistics to estimate them:</li>
</ul>
<p><span class="math display">\[\hat{y}_{i} = b_0 + b_1~x_{i}\]</span></p>
<hr />
</div>
<div id="least-squares-regression" class="section level2">
<h2>Least squares regression</h2>
<ul>
<li>The regression line minimizes the sum of squared residuals.</li>
</ul>
<hr />
<ul>
<li>If <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span>, then, the regression line minimizes
<span class="math inline">\(\sum_{i = 1}^n e_i^2\)</span>.</li>
</ul>
<hr />
</div>
<div id="visualizing-residuals" class="section level2">
<h2>Visualizing residuals</h2>
<p><img src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/figure-html/vis-res-1-1.png" width="70%" /></p>
<hr />
</div>
<div id="visualizing-residuals-cont." class="section level2">
<h2>Visualizing residuals (cont.)</h2>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/figure-html/vis-res-2-1.png" width="70%" /></p>
<hr />
</div>
<div id="visualizing-residuals-cont.-1" class="section level2">
<h2>Visualizing residuals (cont.)</h2>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="https://ramin1ala.netlify.app/posts/fitting-and-interpreting-models/index_files/figure-html/vis-res-3-1.png" width="70%" /></p>
<hr />
</div>
<div id="properties-of-least-squares-regression" class="section level2">
<h2>Properties of least squares regression</h2>
<ul>
<li>The regression line goes through the center of mass point, the coordinates corresponding to average <span class="math inline">\(x\)</span> and average <span class="math inline">\(y\)</span>, <span class="math inline">\((\bar{x}, \bar{y})\)</span>:</li>
</ul>
<p><span class="math display">\[\bar{y} = b_0 + b_1 \bar{x} ~ \rightarrow ~ b_0 = \bar{y} - b_1 \bar{x}\]</span></p>
<hr />
<ul>
<li>The slope has the same sign as the correlation coefficient: <span class="math inline">\(b_1 = r \frac{s_y}{s_x}\)</span></li>
</ul>
<hr />
<ul>
<li>The sum of the residuals is zero: <span class="math inline">\(\sum_{i = 1}^n e_i = 0\)</span></li>
</ul>
<table style="width:4%;">
<colgroup>
<col width="4%" />
</colgroup>
<tbody>
<tr class="odd">
<td>- The residuals and <span class="math inline">\(x\)</span> values are uncorrelated</td>
</tr>
</tbody>
</table>
<p>class: middle</p>
</div>
</div>
<div id="models-with-categorical-explanatory-variables" class="section level1">
<h1>Models with categorical explanatory variables</h1>
<hr />
<div id="categorical-predictor-with-2-levels" class="section level2">
<h2>Categorical predictor with 2 levels</h2>
<p>.pull-left-narrow[
.small[</p>
<pre><code>## # A tibble: 3,393 x 3
##    name      Height_in landsALL
##    &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;
##  1 L1764-2          37        0
##  2 L1764-3          18        0
##  3 L1764-4          13        1
##  4 L1764-5a         14        1
##  5 L1764-5b         14        1
##  6 L1764-6           7        0
##  7 L1764-7a          6        0
##  8 L1764-7b          6        0
##  9 L1764-8          15        0
## 10 L1764-9a          9        0
## 11 L1764-9b          9        0
## 12 L1764-10a        16        1
## 13 L1764-10b        16        1
## 14 L1764-10c        16        1
## 15 L1764-11         20        0
## 16 L1764-12a        14        1
## 17 L1764-12b        14        1
## 18 L1764-13a        15        1
## 19 L1764-13b        15        1
## 20 L1764-14         37        0
## # ... with 3,373 more rows</code></pre>
<p>]
]
.pull-right-wide[
- <code>landsALL = 0</code>: No landscape features
- <code>landsALL = 1</code>: Some landscape features]</p>
<hr />
</div>
<div id="height-landscape-features" class="section level2">
<h2>Height &amp; landscape features</h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ factor(landsALL), data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 2 x 5
##   term              estimate std.error statistic  p.value
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)          22.7      0.328      69.1 0       
## 2 factor(landsALL)1    -5.65     0.532     -10.6 7.97e-26</code></pre>
<hr />
</div>
<div id="height-landscape-features-1" class="section level2">
<h2>Height &amp; landscape features</h2>
<p><span class="math display">\[\widehat{Height_{in}} = 22.7 - 5.645~landsALL\]</span></p>
<ul>
<li><strong>Slope:</strong> Paintings with landscape features are expected, on average, to be 5.645 inches shorter than paintings that without landscape features
<ul>
<li>Compares baseline level (<code>landsALL = 0</code>) to the other level (<code>landsALL = 1</code>)</li>
</ul></li>
<li><strong>Intercept:</strong> Paintings that don’t have landscape features are expected, on average, to be 22.7 inches tall</li>
</ul>
<hr />
</div>
<div id="relationship-between-height-and-school" class="section level2">
<h2>Relationship between height and school</h2>
<pre class="r"><code>linear_reg() %&gt;%
  set_engine(&quot;lm&quot;) %&gt;%
  fit(Height_in ~ school_pntg, data = pp) %&gt;%
  tidy()</code></pre>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
<hr />
</div>
<div id="dummy-variables" class="section level2">
<h2>Dummy variables</h2>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
<ul>
<li>When the categorical explanatory variable has many levels, they’re encoded to <strong>dummy variables</strong></li>
<li>Each coefficient describes the expected difference between heights in that particular school compared to the baseline level</li>
</ul>
<hr />
</div>
<div id="categorical-predictor-with-3-levels" class="section level2">
<h2>Categorical predictor with 3+ levels</h2>
<p>.pull-left-wide[</p>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
school_pntg
</th>
<th style="text-align:center;">
D_FL
</th>
<th style="text-align:center;">
F
</th>
<th style="text-align:center;">
G
</th>
<th style="text-align:center;">
I
</th>
<th style="text-align:center;">
S
</th>
<th style="text-align:center;">
X
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
D/FL
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
F
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
G
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
I
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(68, 1, 84, 1) !important;">
0
</td>
<td style="text-align:center;width: 10em; color: white !important;background-color: rgba(122, 209, 81, 1) !important;">
1
</td>
</tr>
</tbody>
</table>
<p>]
.pull-right-narrow[
.small[</p>
<pre><code>## # A tibble: 3,393 x 3
##    name      Height_in school_pntg
##    &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;      
##  1 L1764-2          37 F          
##  2 L1764-3          18 I          
##  3 L1764-4          13 D/FL       
##  4 L1764-5a         14 F          
##  5 L1764-5b         14 F          
##  6 L1764-6           7 I          
##  7 L1764-7a          6 F          
##  8 L1764-7b          6 F          
##  9 L1764-8          15 I          
## 10 L1764-9a          9 D/FL       
## 11 L1764-9b          9 D/FL       
## 12 L1764-10a        16 X          
## 13 L1764-10b        16 X          
## 14 L1764-10c        16 X          
## 15 L1764-11         20 D/FL       
## 16 L1764-12a        14 D/FL       
## 17 L1764-12b        14 D/FL       
## 18 L1764-13a        15 D/FL       
## 19 L1764-13b        15 D/FL       
## 20 L1764-14         37 F          
## # ... with 3,373 more rows</code></pre>
<p>]
]</p>
<hr />
</div>
<div id="relationship-between-height-and-school-1" class="section level2">
<h2>Relationship between height and school</h2>
<p>.small[</p>
<pre><code>## # A tibble: 7 x 5
##   term            estimate std.error statistic p.value
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)        14.0       10.0     1.40  0.162  
## 2 school_pntgD/FL     2.33      10.0     0.232 0.816  
## 3 school_pntgF       10.2       10.0     1.02  0.309  
## 4 school_pntgG        1.65      11.9     0.139 0.889  
## 5 school_pntgI       10.3       10.0     1.02  0.306  
## 6 school_pntgS       30.4       11.4     2.68  0.00744
## 7 school_pntgX        2.87      10.3     0.279 0.780</code></pre>
<ul>
<li><strong>Austrian school (A)</strong> paintings are expected, on average, to be <strong>14 inches</strong> tall.</li>
<li><strong>Dutch/Flemish school (D/FL)</strong> paintings are expected, on average, to be <strong>2.33 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>French school (F)</strong> paintings are expected, on average, to be <strong>10.2 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>German school (G)</strong> paintings are expected, on average, to be <strong>1.65 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Italian school (I)</strong> paintings are expected, on average, to be <strong>10.3 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li><strong>Spanish school (S)</strong> paintings are expected, on average, to be <strong>30.4 inches taller</strong> than <em>Austrian school</em> paintings.</li>
<li>Paintings whose school is <strong>unknown (X)</strong> are expected, on average, to be <strong>2.87 inches taller</strong> than <em>Austrian school</em> paintings.
]</li>
</ul>
</div>
</div>

    </div>
    <div class="post-footer">
      
    </div>
  </article>

    </main>
  </body>
</html>
