---
title: Project
author: ''
date: '2021-06-22'
slug: []
categories: []
tags:
  - data_visualization
  - data_wrangling
  - R
---

**Ramin Ala**





```{r packages, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(tidymodels) #Interesting collections of models.
library(ggtext) #similar to ggplot but for text.
library(knitr)
library(kableExtra) 
library(janitor)
library(gganimate)
library(gifski)
```



---

## Import Data: Energy & Mining


```{r, echo=FALSE, message=FALSE, include=TRUE, warning=FALSE}
air <- read_csv("AirQualityUCI.csv", na = c("n/a", "", "NA")) %>%
  janitor::clean_names() 
names(air)
```






```{r}
ee <- air %>%
  select(co_gt,pt08_s1_co) %>%
subset(co_gt!=-200 & pt08_s1_co!=-200) %>%
 
  ggplot(aes(co_gt,pt08_s1_co))+
  geom_point()+
  geom_smooth(method = "lm", se = FALSE, color = "#8E2C90")

ee
```

```{r}
fgfg <- linear_reg() %>%
  set_engine("lm") %>%
  fit(co_gt~pt08_s1_co, data = air) %>%
  tidy()


fgfg
```


https://archive.ics.uci.edu/ml/datasets/Air+Quality
